/**
 * Delivery and Logistics Constants
 */

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export type NigerianState = (typeof NIGERIAN_STATES)[number];

export const NIGERIAN_CITIES_BY_STATE: Record<string, string[]> = {
  Lagos: [
    "Ikeja",
    "Lekki",
    "Victoria Island",
    "Ikoyi",
    "Surulere",
    "Yaba",
    "Maryland",
    "Magodo",
    "Gbagada",
    "Ajah",
    "Ogudu",
    "Festac Town",
    "Oshodi",
    "Ikorodu",
    "Alimosho",
    "Agege",
    "Apapa",
  ],
  "FCT - Abuja": [
    "Wuse",
    "Wuse 2",
    "Garki",
    "Maitama",
    "Asokoro",
    "Gwarinpa",
    "Central Business District",
    "Jabi",
    "Utako",
    "Kubwa",
    "Lugbe",
    "Apo",
    "Guzape",
    "Life Camp",
  ],
  Rivers: [
    "Port Harcourt",
    "Obio-Akpor",
    "Trans Amadi",
    "GRA Phase 1",
    "GRA Phase 2",
    "D-Line",
    "Woji",
    "Eleme",
    "Oyigbo",
  ],
  Oyo: [
    "Ibadan (Bodija)",
    "Ibadan (Ring Road)",
    "Ibadan (Oluyole)",
    "Ibadan (Jericho)",
    "Ibadan (Samonda)",
    "Ibadan (Dugbe)",
    "Ogbomosho",
    "Oyo Town",
  ],
  Ogun: ["Abeokuta", "Ota", "Arepo", "Magboro", "Mowe", "Ibafo", "Sagamu", "Ijebu Ode"],
  Kano: ["Kano Municipal", "Nassarawa", "Fagge", "Dala", "Gwale", "Tarauni"],
  Delta: ["Warri", "Asaba", "Effurun", "Sapele", "Ughelli"],
  Edo: ["Benin City", "GRA Benin", "Uselu", "Ikpoba Okha", "Egor"],
  Enugu: [
    "Enugu North (Independence Layout)",
    "Enugu South",
    "Enugu East (Trans-Ekulu)",
    "New Haven",
    "Achara Layout",
  ],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  Kaduna: ["Kaduna North", "Kaduna South", "Barnawa", "Malali", "Zaria"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron"],
  "Cross River": ["Calabar Municipal", "Calabar South"],
  Kwara: ["Ilorin", "GRA Ilorin", "Tanke", "Offa"],
  Osun: ["Osogbo", "Ile-Ife", "Ede", "Ilesa"],
  Ondo: ["Akure", "Ondo Town", "Owo"],
  Plateau: ["Jos North", "Jos South", "Rayfield", "Bukuru"],
  Imo: ["Owerri Municipal", "Owerri North", "Owerri West", "Orlu"],
  Abia: ["Umuahia", "Aba", "Aba North", "Aba South"],
};
